[package]
name = "termixel"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = { version = "0.8.2" }

[[bench]]
name = "sprite_rendering"
harness = false

[dependencies]
png = { version = "0.18.1", default-features = false }

[profile.release]

# Strip symbols from the binary
strip = true

# Optimize for size
opt-level = "z"

# Enable link-time optimization
lto = "fat"

# Reduce codegen units to minimize binary size and improve performance
codegen-units = 1

# Abort on panic to minimize binary size
panic = "abort"
